[package]
name = "pg_catalog_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arrow = "55.0.0"
datafusion = "47.0.0"
datafusion_pg_catalog = { git = "https://github.com/ybrs/pg_catalog" }
rusqlite = "0.36.0"
tokio = { version = "1.45.1", features = ["full"] }
