public: # catalog
  crm: # schema
    users: # table
      schema:
        id: uuid
        name: varchar(120)
        role_id: uuid
        created_at: datetime
      rows:
        - id: "123e4567-e89b-12d3-a456-426614174000"
          name: "Alice"
          role_id: "abc123"
          created_at: "2024-01-01T12:00:00"
        - id: "223e4567-e89b-12d3-a456-426614174000"
          name: "Bob"
          role_id: "abc123"
          created_at: "2024-01-02T13:00:00"
    roles:
      schema:
        id: uuid
        name: varchar(120)
      rows:
        - id: "abc123"
          name: "admin"
