public:
  pg_catalog:
    pg_ts_config:
      type: system_catalog
      schema:
        oid: int
        cfgname: varchar(64)
        cfgnamespace: int
        cfgowner: int
        cfgparser: int
      pg_types:
        oid: oid
        cfgname: name
        cfgnamespace: oid
        cfgowner: oid
        cfgparser: oid
      rows:
      - oid: 3748
        cfgname: simple
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12727
        cfgname: arabic
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12729
        cfgname: armenian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12731
        cfgname: basque
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12733
        cfgname: catalan
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12735
        cfgname: danish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12737
        cfgname: dutch
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12739
        cfgname: english
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12741
        cfgname: finnish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12743
        cfgname: french
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12745
        cfgname: german
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12747
        cfgname: greek
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12749
        cfgname: hindi
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12751
        cfgname: hungarian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12753
        cfgname: indonesian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12755
        cfgname: irish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12757
        cfgname: italian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12759
        cfgname: lithuanian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12761
        cfgname: nepali
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12763
        cfgname: norwegian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12765
        cfgname: portuguese
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12767
        cfgname: romanian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12769
        cfgname: russian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12771
        cfgname: serbian
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12773
        cfgname: spanish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12775
        cfgname: swedish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12777
        cfgname: tamil
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12779
        cfgname: turkish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
      - oid: 12781
        cfgname: yiddish
        cfgnamespace: 11
        cfgowner: 10
        cfgparser: 3722
